spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnect=true
    validationQuery: SELECT 1
    testOnBorrow: true
    validationInterval: 60000
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
globally_quoted_identifiers: true